//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.17379
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanaphoNews.Localization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NanaphoNews.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_AppBar_IconButtonText_Cancel {
            get {
                return ResourceManager.GetString("Common_AppBar_IconButtonText_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_AppBar_IconButtonText_Complete {
            get {
                return ResourceManager.GetString("Common_AppBar_IconButtonText_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   refresh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_AppBar_MenuItemText_Refresh {
            get {
                return ResourceManager.GetString("Common_AppBar_MenuItemText_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Just a moment... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ToggleSwitch_Content_Off {
            get {
                return ResourceManager.GetString("Common_ToggleSwitch_Content_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   On に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ToggleSwitch_Content_On {
            get {
                return ResourceManager.GetString("Common_ToggleSwitch_Content_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_AppBar_MenuItemText_AboutTheApplication {
            get {
                return ResourceManager.GetString("MainPage_AppBar_MenuItemText_AboutTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t retrieve data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_Error_FailedToGetAllFeedGroupsAndChannels {
            get {
                return ResourceManager.GetString("MainPage_Error_FailedToGetAllFeedGroupsAndChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   nanapho news に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_PivotTitle {
            get {
                return ResourceManager.GetString("MainPage_PivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Details and reviews for the app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_ApplicationDetailsAndReviews {
            get {
                return ResourceManager.GetString("PreferencesPage_ApplicationDetailsAndReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   nanapho news に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_ApplicationTitle {
            get {
                return ResourceManager.GetString("PreferencesPage_ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_ApplicationVersion {
            get {
                return ResourceManager.GetString("PreferencesPage_ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration failed. Please retry later. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_Error_NotificationRegistrationFailed {
            get {
                return ResourceManager.GetString("PreferencesPage_Error_NotificationRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open app details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_GotoApplicationDetails {
            get {
                return ResourceManager.GetString("PreferencesPage_GotoApplicationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Push notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_Notification_ReceiveNotification {
            get {
                return ResourceManager.GetString("PreferencesPage_Notification_ReceiveNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation of push notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_Notification_ReceiveNotification_ConfirmationCaption {
            get {
                return ResourceManager.GetString("PreferencesPage_Notification_ReceiveNotification_ConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabling push notification, you can receive tile and toast notification for nanapho&apos;s updates. You can turn this functionality off anytime. Do you want to enable this functionality? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_Notification_ReceiveNotification_ConfirmationText {
            get {
                return ResourceManager.GetString("PreferencesPage_Notification_ReceiveNotification_ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can receive tile and toast notification for nanapho&apos;s updates. Pin this app to your start screen to receive tile notification. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_Notification_ReceiveNotificationDesc {
            get {
                return ResourceManager.GetString("PreferencesPage_Notification_ReceiveNotificationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SETTINGS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_PageHeaderTitle {
            get {
                return ResourceManager.GetString("PreferencesPage_PageHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   about the app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_PivotItem_AboutTheApplication {
            get {
                return ResourceManager.GetString("PreferencesPage_PivotItem_AboutTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_PivotItem_Notification {
            get {
                return ResourceManager.GetString("PreferencesPage_PivotItem_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Twitter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_TwitterAccountForSupport {
            get {
                return ResourceManager.GetString("PreferencesPage_TwitterAccountForSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @yamac_support に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_TwitterAccountForSupportValue {
            get {
                return ResourceManager.GetString("PreferencesPage_TwitterAccountForSupportValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   open with browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebPage_AppBar_MenuItemText_OpenWithBrowser {
            get {
                return ResourceManager.GetString("WebPage_AppBar_MenuItemText_OpenWithBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   share the page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebPage_AppBar_MenuItemText_ShareThePage {
            get {
                return ResourceManager.GetString("WebPage_AppBar_MenuItemText_ShareThePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check your cellular data or Wi-Fi connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebPage_Error_NavigationFailedMessage {
            get {
                return ResourceManager.GetString("WebPage_Error_NavigationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The page cannot be displayed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebPage_Error_NavigationFailedTitle {
            get {
                return ResourceManager.GetString("WebPage_Error_NavigationFailedTitle", resourceCulture);
            }
        }
    }
}
